# Generated by Django 5.0.6 on 2024-07-15 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тема обращения',
                'verbose_name_plural': 'Темы обращений',
                'db_table': 'orders_topics',
            },
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ПО',
                'verbose_name_plural': 'ПО',
                'db_table': 'soft',
            },
        ),
        migrations.CreateModel(
            name='UsedSoft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_soft', to='client_app.soft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_soft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ПО пользователей',
                'verbose_name_plural': 'ПО пользователей',
                'db_table': 'used_soft',
            },
        ),
    ]
