# Generated by Django 5.0.6 on 2024-07-17 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 0, 20, 20, 340425), verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 0, 20, 20, 340453), verbose_name='Обновлена'),
        ),
    ]
