# Generated by Django 5.0.6 on 2024-07-17 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_news_created_at_alter_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 0, 22, 4, 333011), verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 0, 22, 4, 333039), verbose_name='Обновлена'),
        ),
    ]
